# Build Environment
FROM node:22-alpine AS build

# Set working directory
WORKDIR /app

ARG 

# Copy file penting untuk install dependencies
COPY package.json package-lock.json ./

# Instal package secara clean
RUN npm ci

# Copy seluruh source code
COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]